spool log/drop_tab.log;

drop sequence TMP_PROD_ID_SEQ;
drop sequence TMP_NR_REF_SEQ;
/* drop sequence TMP_NR_UM_SEQ;
drop sequence TMP_DOK_PROD_ID_SEQ;

drop sequence IF1_KLIENT_TMP_ID_SEQ;
drop sequence IF1_KLIENT_TMP_KOD_SEQ;
drop sequence IF1_UMOWY_TMP_ID_SEQ;

drop sequence TMP_CC_NR_KARTY_SEQ;

drop TABLE KLIENCI_ID_TMP;
drop TABLE ANALITYKA_ID_TMP;
drop TABLE WNIOSKI_ID_TMP;
drop TABLE UMOWY_ID_TMP;
drop TABLE ANEKSY_ID_TMP;
drop TABLE UMOWY_HARMONOGRAMY_ID_TMP;
drop TABLE UMOWY_HARM_POZYCJE_ID_TMP;
drop TABLE UMOWY_REJESTRY_TMP;
drop TABLE DOKUMENTY_ID_TMP;
drop TABLE KLIENCI_TMP;
drop table ANALITYKA_TMP;
drop TABLE WNIOSKI_TMP;
drop TABLE UMOWY_TMP;
drop TABLE ANEKSY_TMP;
drop TABLE UMOWY_HARMONOGRAMY_TMP;
drop TABLE UMOWY_HARM_POZYCJE_TMP;
drop TABLE DOKUMENTY_TMP;
drop TABLE DEKRETY_TMP;

drop table IF1_KLIENCI_TMP;
drop table IF1_KLIENCI_ID_TMP;

drop table IF1_RACHUNKI_NOSTRO_TMP;
drop table IF1_RACHUNKI_NOSTRO_ID_TMP;
drop table IF1_UMOWY_TMP;
drop table IF1_UMOWY_ID_TMP;

drop table CC_KARTY_PLATNICZE_TMP;
drop table CC_KARTY_PLATNICZE_ID_TMP; */

spool off;

